name: Nas-tools Build
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - version.py

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Release version
      id: release_version
      run: |
        app_version=$(cat version.py |sed -ne "s/APP_VERSION\s=\s'v\(.*\)'/\1/gp")
        echo "app_version=$app_version" >> $GITHUB_ENV
    - name: Create release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.app_version }}
        release_name: v${{ env.app_version }}
        body: ${{ github.event.commits[0].message }}
        draft: false
        prerelease: false
    - name: output release_informations
      run: |
        echo "${{ steps.create_release.outputs.id }}" > release_id.txt
        echo "${{ env.app_version }}" > app_version.txt
    - name: save release_informations
      uses: actions/upload-artifact@v3
      with:
        name: release_informations
        path: |
          release_id.txt
          app_version.txt

  synology-build:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
    - name: download release_informations
      uses: actions/download-artifact@v3
    - name: get app_version
      shell: bash
      run: |
        value=`cat release_informations/app_version.txt`
        echo "app_version=$value" >> $GITHUB_ENV
    - name: Build the synology spk
      run: |
        git clone https://github.com/jxxghp/nas-tools
        cd nas-tools
        cp -r synology/ui synology/wheelhouse ./
        sed -i 's/3000/3003/g' config/config.yaml
        sed -i 's/\/config\/logs/\/var\/packages\/nastool\/target\/config\/logs/g' config/config.yaml
        tar -zcvf package.tgz *.py *.txt service/ rmt/ message/ web/ ui/ wheelhouse/ config/ pt/ utils/
        mkdir spk6
        cp -r package.tgz synology/dsm6/conf synology/dsm6/scripts/ synology/dsm6/INFO synology/CHANGELOG synology/*.PNG synology/*.asc spk6/
        cd spk6/
        chmod 777 scripts/*
        sed -i 's/NASTOOL_VERSION/${{ env.app_version }}/g' INFO
        tar -cvf nastool_dsm_6.x.spk *
        cd ..
        rm -f package.tgz
        tar -zcvf package.tgz *.py *.txt service/ rmt/ message/ web/ ui/ wheelhouse/ config/ pt/ utils/
        mkdir spk7
        cp -r package.tgz synology/dsm7/conf synology/dsm7/scripts/ synology/dsm7/INFO synology/CHANGELOG synology/*.PNG synology/*.asc spk7/
        cd spk7/
        chmod 777 scripts/*
        sed -i 's/NASTOOL_VERSION/${{ env.app_version }}/g' INFO
        tar -cvf nastool_dsm_7.x.spk *
        cd ..
        mkdir spks
        mv spk6/nastool_dsm_6.x.spk spk7/nastool_dsm_7.x.spk spks/
    - name: upload synology files
      uses: actions/upload-artifact@v3
      with:
        name: synology
        path: /home/runner/work/nas-tools/nas-tools/nas-tools/spks/

  windows-build:
    runs-on: windows-latest
    needs: create-release
    steps:
    - name: init Python 3.10.6
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.6'
    - name: install dependent packages
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install numpy
        pip install railroad
        pip install pyparsing
        pip install wxpython
        pip install pyinstaller
        git clone https://github.com/jxxghp/nas-tools
        cd nas-tools
        pip install -r requirements.txt
    - name: package through pyinstaller
      run:
        cd nas-tools &&
        copy .\windows\rely\upx.exe c:\hostedtoolcache\windows\python\3.10.6\x64\Scripts &&
        copy .\windows\rely\hook-cn2an.py c:\hostedtoolcache\windows\python\3.10.6\x64\lib\site-packages\pyinstaller\hooks &&
        copy .\windows\rely\hook-zhconv.py c:\hostedtoolcache\windows\python\3.10.6\x64\lib\site-packages\pyinstaller\hooks &&
        copy .\windows\rely\template.jinja2 c:\hostedtoolcache\windows\Python\3.10.6\x64\lib\site-packages\setuptools\_vendor\pyparsing\diagram &&
        xcopy .\web c:\hostedtoolcache\windows\python\3.10.6\x64\lib\site-packages\web\ /e &&
        cd windows &&
        pyinstaller nas-tools.spec /
    - name: upload windows file
      uses: actions/upload-artifact@v3
      with:
        name: windows
        path: D:/a/nas-tools/nas-tools/nas-tools/windows/dist/nas-tools.exe

  Send-message:
    runs-on: ubuntu-latest
    needs: [synology-build, windows-build]
    steps:
    - name: download release_informations
      uses: actions/download-artifact@v3
    - name: get release_informations
      shell: bash
      run: |
        value=`cat release_informations/release_id.txt`
        echo "release_id=$value" >> $GITHUB_ENV
        value=`cat release_informations/app_version.txt`
        echo "app_version=$value" >> $GITHUB_ENV
    - name: Upload release asset
      uses: dwenegar/upload-release-assets@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ env.release_id }}
        assets_path: |
            /home/runner/work/nas-tools/nas-tools/synology/
            /home/runner/work/nas-tools/nas-tools/windows/
    - name: Send telegram message (release informations)
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: |
            *v${{ env.app_version }}*

            ${{ github.event.commits[0].message }}
    - name: Send telegram message synology 1
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_XM }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        document: /home/runner/work/nas-tools/nas-tools/synology/nastool_dsm_6.x.spk
    - name: Send telegram message synology 2
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_XM }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        document: /home/runner/work/nas-tools/nas-tools/synology/nastool_dsm_7.x.spk
    - name: Send telegram message windows
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_XM }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        document: /home/runner/work/nas-tools/nas-tools/windows/nas-tools.exe
